### ISSUE TITLE
visualize single entity

### ISSUE THREAD

**Issue by chicco785** [orchestracities/auth-management-ui#116]
Display an entity dialog with two tabs:

* View tab. Contains a table showing the entity attrs. Plus, if there's a location attr, we display a map with a pin. For JSON attrs, just show a preview, then the user can click to see the whole content.
* JSON tab. Shows the JSON entity as received from Context Broker.

See screenshot

![6DEB03F9-F701-45BA-8022-EB6EF31A008B](https://user-images.githubusercontent.com/13233181/217207984-be101e87-d1b1-4728-b175-79293c66a560.jpg)

**Comment by Valecant** [comment]
Maybe a solution for the display of a single table that can be used for the detail without displaying the whole JSON or open a new modal:
https://mui.com/material-ui/react-table/#collapsible-table
