### ISSUE TITLE
fix documentation for service path filter

### ISSUE THREAD

**Issue by chicco785** [orchestracities/auth-management-ui#131]
**Describe the bug**

In the documentation storybook, service path filter is not configured nor in Policy not in Entity (probably @chicco785 changed something that caused the issue while cleaning up #124)

**To Reproduce**
1. Open the documentation for policy filters.
 
**Expected behavior**

N/A

**Comment by Valecant** [comment]
No, the problem was more simple, i just forgot to populate the values that storybook is passing to the component, adding them i fixed the issue.
without any value the filter is automatically disable
