### ISSUE TITLE
row check box not displayed in resourceType table

### ISSUE THREAD

**Issue by chicco785** [orchestracities/auth-management-ui#139]
**Describe the bug**

The check box is not visible for each resource listed.

**To Reproduce**

1. Access resource type page
2. See error

**Expected behavior**

Check box are visible

**Environment (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/777218/208527809-7eeaeac3-edfc-4d4b-bf71-48c6c8b8c6c4.png)

**Comment by Valecant** [comment]
They weren't rendered for design choice, still undecided if is necessary to remove them in the other tables (a part from the select all) for design reasons, I think that looks cleaner without them.

**Comment by chicco785** [comment]
> They weren't rendered for design choice, still undecided if is necessary to remove them in the other tables (a part from the select all) for design reasons, I think that looks cleaner without them.

1. The weird thing is that they are not visible, but you can actually check them. So if the idea was not to have them, there's a bug.
2. Functionally speaking, how is a user supposed to delete only a single entry?

**Comment by Valecant** [comment]
> > They weren't rendered for design choice, still undecided if is necessary to remove them in the other tables (a part from the select all) for design reasons, I think that looks cleaner without them.
> 
> 1. The weird thing is that they are not visible, but you can actually check them. So if the idea was not to have them, there's a bug.
> 2. Functionally speaking, how is a user supposed to delete only a single entry?

You can select the row just clicking on it, and then deleting them using the delete button on the up right.
On the checkbox implementation you can also select the row clicking on it

**Comment by chicco785** [comment]
> > > They weren't rendered for design choice, still undecided if is necessary to remove them in the other tables (a part from the select all) for design reasons, I think that looks cleaner without them.
> > 
> > 
> > 
> > 1. The weird thing is that they are not visible, but you can actually check them. So if the idea was not to have them, there's a bug.
> > 2. Functionally speaking, how is a user supposed to delete only a single entry?
> 
> You can select the row just clicking on it, and then deleting them using the delete button on the up right. On the tables with a checkbox implementation you can also select the row clicking on it and not necessarily on the checkbox. I don't really like the checkboxes repeated especially on mobile when you have a lot of data

I got it know -> selection is made but the check box is not available, you can guess what is selected by the color difference. On my screen the difference between selected and not selected is not very visible (which is probably the cause of my initial not understanding of what's going on there), let's make it more visible.
