### ISSUE TITLE
remove edit from service path

### ISSUE THREAD

**Issue by chicco785** [orchestracities/auth-management-ui#61]
**Describe the bug**
The API does not support the edit of service paths, so the ui should not as well. 

The rational for not supporting the edit it's very important:
- a servicePath is attached to data (and in a different api), so changing it will not affect the apis where the data are stored. 
- in practise this means that if change a path from /a to /b:
    - if i try to access data in /a, i will get a reject policy wise (/a does not exist anymore)
    - if i try to access data in /b, i will get a not found (data are still with service path /b)

**Comment by Valecant** [comment]
I don't think that the edit on the services is active, the edit icon is related to the creation on a sub-service if clicked i will open the form to the children creation (explained on the tooltip).
what i can do is to change the icon from the edit one to something more clear

**Comment by chicco785** [comment]
then the icon should be a plus not a pencil

**Comment by chicco785** [comment]
also, it's unclear to me how to add a subpath to level 2 subpath in the current view

**Comment by Valecant** [comment]
> also, it's unclear to me how to add a subpath to level 2 subpath in the current view

so is possibile to create path/subpath/subpath ?.
in that case not a big issue i have already got an idea

**Comment by chicco785** [comment]
levels are unlimited
